INSERT INTO lms.genre (genre_name) VALUES ('Action and adventure');
INSERT INTO lms.genre (genre_name) VALUES ('Alternate history');
INSERT INTO lms.genre (genre_name) VALUES ('Anthology');
INSERT INTO lms.genre (genre_name) VALUES ('Chick lit');
INSERT INTO lms.genre (genre_name) VALUES ('Children''s');
INSERT INTO lms.genre (genre_name) VALUES ('Comic book');
INSERT INTO lms.genre (genre_name) VALUES ('Coming-of-age');
INSERT INTO lms.genre (genre_name) VALUES ('Crime');
INSERT INTO lms.genre (genre_name) VALUES ('Drama');
INSERT INTO lms.genre (genre_name) VALUES ('Fairytale');
INSERT INTO lms.genre (genre_name) VALUES ('Fantasy');
INSERT INTO lms.genre (genre_name) VALUES ('Graphic novel');
INSERT INTO lms.genre (genre_name) VALUES ('Historical fiction');
INSERT INTO lms.genre (genre_name) VALUES ('Horror');
INSERT INTO lms.genre (genre_name) VALUES ('Mystery');
INSERT INTO lms.genre (genre_name) VALUES ('Paranormal romance');
INSERT INTO lms.genre (genre_name) VALUES ('Picture book');
INSERT INTO lms.genre (genre_name) VALUES ('Poetry');
INSERT INTO lms.genre (genre_name) VALUES ('Political thriller');
INSERT INTO lms.genre (genre_name) VALUES ('Romance');
INSERT INTO lms.genre (genre_name) VALUES ('Satire');
INSERT INTO lms.genre (genre_name) VALUES ('Science fiction');
INSERT INTO lms.genre (genre_name) VALUES ('Short story');
INSERT INTO lms.genre (genre_name) VALUES ('Suspense');
INSERT INTO lms.genre (genre_name) VALUES ('Thriller');
INSERT INTO lms.genre (genre_name) VALUES ('Young adult');
INSERT INTO lms.genre (genre_name) VALUES ('Art');
INSERT INTO lms.genre (genre_name) VALUES ('Autobiography');
INSERT INTO lms.genre (genre_name) VALUES ('Biography');
INSERT INTO lms.genre (genre_name) VALUES ('Book review');
INSERT INTO lms.genre (genre_name) VALUES ('Cookbook');
INSERT INTO lms.genre (genre_name) VALUES ('Diary');
INSERT INTO lms.genre (genre_name) VALUES ('Dictionary');
INSERT INTO lms.genre (genre_name) VALUES ('Encyclopedia');
INSERT INTO lms.genre (genre_name) VALUES ('Guide');
INSERT INTO lms.genre (genre_name) VALUES ('Health');
INSERT INTO lms.genre (genre_name) VALUES ('History');
INSERT INTO lms.genre (genre_name) VALUES ('Journal');
INSERT INTO lms.genre (genre_name) VALUES ('Math');
INSERT INTO lms.genre (genre_name) VALUES ('Memoir');
INSERT INTO lms.genre (genre_name) VALUES ('Prayer');
INSERT INTO lms.genre (genre_name) VALUES ('Religion, spirituality, and new age');
INSERT INTO lms.genre (genre_name) VALUES ('Textbook');
INSERT INTO lms.genre (genre_name) VALUES ('Review');
INSERT INTO lms.genre (genre_name) VALUES ('Science');
INSERT INTO lms.genre (genre_name) VALUES ('Self help');
INSERT INTO lms.genre (genre_name) VALUES ('Travel');
INSERT INTO lms.genre (genre_name) VALUES ('True crime');
