INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Adekunle Gold','Musician','M','9997696334','adekunle.gold@hotmail.com','7364 N. Branch Street,Norcross, GA 30092');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('John Kenedy','President','M','5509731057','johnkenedy@aol.com','1 Cedar Swamp St., West Chester, PA 19380');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Gaven Arroyo','Student','M','7207563352','gaven.arroyo@gmail.com','936 North Riverside St., Livingston, NJ 07039');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Kimberly Mathis','Doctor','F','8187807021','kimberlymathis@yahoo.com','843 Park Ave.Superior, WI 54880');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Karley Mendoza','Lawyer','F','8924468102','karley.mendoza@gmail.com','7178 Monroe Street, Coventry, RI 02816');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Hudson Guerrero','Military','M','3929470139','hudson_guerrero@yahoo.com','363 South Forest Drive, Downingtown, PA 19335');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Dillon Perkins','Student','M','7978043248','dillon_perkins@yahoo.com','6 Greenrose Ave.Forest Hills, NY 11375');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Tiffany Howard','Lawyer','F','9154022365','tiffany.howard@sbcglobal.net','5 Stillwater Ave.Marshalltown, IA 50158');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Laci Mack','Engineer','M','5437835213','laci.mack@sbcglobal.net','238 Hillside Street, Beaver Falls, PA 15010');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Brock Vaughan','Teacher','M','6948190970','brockvaughan@aol.com','327 Newbridge Ave.Charlotte, NC 28205');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Kamryn Franco','Nurse','F','6958816202','kamrynfranco@hotmail.com','638 Oxford St.Forney, TX 75126');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Leland Humphrey','Student','M','3963132116','leland.humphrey@yahoo.com','125 Berkshire Lane, Gainesville, VA 20155');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Delaney Hayes','Programmer','M','3665484536','delaneyhayes@yahoo.com','41 Newcastle Drive, Little Rock, AR 72209');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Bryce Reilly','Construction worker','M','8175291808','bryce.reilly@hotmail.com','625 Cedar Drive, Starkville, MS 39759');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Dominick Sutton','Accountant','M','9245083521','dominicksutton@sbcglobal.net','7756 Longbranch Ave.Rockledge, FL 32955');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Melanie Lang','Electrician','F','4942677915','melanielang@yahoo.com','535 North Annadale Drive, San Jose, CA 95127');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Jorge Ellison','Student','M','4295990856','jorge.ellison@gmail.com','8237 Arrowhead St.Derry, NH 03038');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Danny Wise','Firefighter','M','2229480869','dannywise@me.com','45 W. Shore Rd.Janesville, WI 53546');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Juan Wheeler','Chef','M','9815919789','juan.wheeler@gmail.com','248 NE. Willow Ave.Cincinnati, OH 45211');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Claudia Franco','Artist','M','6934956665','claudia_franco@me.com','9186 Saxton Road. New Orleans, LA 70115');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Todd Craig','Student','M','8477237811','todd_craig@hotmail.com','8563 Harvard Court, Muskegon, MI 49441');
INSERT INTO lms.member (name,occupation,gender,phone_number,email,address) VALUES ('Dominick George','Dentist','M','7872849405','dominick.george@yahoo.com','83 Van Dyke St.Floral Park, NY 11001');
