-- MySQL Script generated by MySQL Workbench
-- Thu Jan 26 22:04:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lms` ;

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lms` DEFAULT CHARACTER SET utf8mb4 ;
USE `lms` ;

-- -----------------------------------------------------
-- Table `lms`.`publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`publisher` ;

CREATE TABLE IF NOT EXISTS `lms`.`publisher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NULL,
  `phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `establishment_date` DATE NULL,
  `isbn_prefix` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`book` ;

CREATE TABLE IF NOT EXISTS `lms`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `publisher_id` INT NOT NULL,
  `edition` INT NULL DEFAULT 1,
  `total_pages` INT NOT NULL,
  `format` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `publication_date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `fk_book_publisher_idx` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_publisher`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `lms`.`publisher` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`genre` ;

CREATE TABLE IF NOT EXISTS `lms`.`genre` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`book_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`book_genre` ;

CREATE TABLE IF NOT EXISTS `lms`.`book_genre` (
  `book_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `genre_id`),
  INDEX `fk_book_has_genre_genre1_idx` (`genre_id` ASC) VISIBLE,
  INDEX `fk_book_has_genre_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_has_genre_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `lms`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_has_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `lms`.`genre` (`genre_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`author` ;

CREATE TABLE IF NOT EXISTS `lms`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dob` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`book_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`book_author` ;

CREATE TABLE IF NOT EXISTS `lms`.`book_author` (
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `author_id`),
  INDEX `fk_book_has_author_author1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_book_has_author_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_has_author_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `lms`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_has_author_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `lms`.`author` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`user` ;

CREATE TABLE IF NOT EXISTS `lms`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `occupation` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`library_branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`library_branch` ;

CREATE TABLE IF NOT EXISTS `lms`.`library_branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `hours_of_operation` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `capacity` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`lms_access_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`lms_access_level` ;

CREATE TABLE IF NOT EXISTS `lms`.`lms_access_level` (
  `access_level` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`access_level`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`librarian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`librarian` ;

CREATE TABLE IF NOT EXISTS `lms`.`librarian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `ssn` VARCHAR(45) NOT NULL,
  `emergency_contact` VARCHAR(200) NOT NULL,
  `library_branch_id` INT NOT NULL,
  `access_level` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_librarian_library_branch1_idx` (`library_branch_id` ASC) VISIBLE,
  INDEX `fk_librarian_lms_access_level1_idx` (`access_level` ASC) VISIBLE,
  CONSTRAINT `fk_librarian_library_branch1`
    FOREIGN KEY (`library_branch_id`)
    REFERENCES `lms`.`library_branch` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_librarian_lms_access_level1`
    FOREIGN KEY (`access_level`)
    REFERENCES `lms`.`lms_access_level` (`access_level`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`book_copies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`book_copies` ;

CREATE TABLE IF NOT EXISTS `lms`.`book_copies` (
  `library_branch_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `no_of_copies` INT NULL DEFAULT 0,
  PRIMARY KEY (`library_branch_id`, `book_id`),
  INDEX `fk_library_branch_has_book_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_library_branch_has_book_library_branch1_idx` (`library_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_library_branch_has_book_library_branch1`
    FOREIGN KEY (`library_branch_id`)
    REFERENCES `lms`.`library_branch` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_library_branch_has_book_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `lms`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`loan_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lms`.`loan_record` ;

CREATE TABLE IF NOT EXISTS `lms`.`loan_record` (
  `user_id` INT NOT NULL,
  `library_branch_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `loan_date` DATETIME NOT NULL,
  `due_date` DATETIME NOT NULL,
  `date_in` DATETIME NULL,
  PRIMARY KEY (`user_id`, `library_branch_id`, `book_id`, `loan_date`),
  INDEX `fk_loan_record_library_branch1_idx` (`library_branch_id` ASC) VISIBLE,
  INDEX `fk_loan_record_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_loan_record_member1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lms`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loan_record_library_branch1`
    FOREIGN KEY (`library_branch_id`)
    REFERENCES `lms`.`library_branch` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_loan_record_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `lms`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
