-- genre
INSERT INTO lms.genre (genre_name) VALUES ('Action and adventure');
INSERT INTO lms.genre (genre_name) VALUES ('Alternate history');
INSERT INTO lms.genre (genre_name) VALUES ('Anthology');
INSERT INTO lms.genre (genre_name) VALUES ('Chick lit');
INSERT INTO lms.genre (genre_name) VALUES ('Children''s');
INSERT INTO lms.genre (genre_name) VALUES ('Comic book');
INSERT INTO lms.genre (genre_name) VALUES ('Coming-of-age');
INSERT INTO lms.genre (genre_name) VALUES ('Crime');
INSERT INTO lms.genre (genre_name) VALUES ('Drama');
INSERT INTO lms.genre (genre_name) VALUES ('Fairytale');
INSERT INTO lms.genre (genre_name) VALUES ('Fantasy');
INSERT INTO lms.genre (genre_name) VALUES ('Graphic novel');
INSERT INTO lms.genre (genre_name) VALUES ('Historical fiction');
INSERT INTO lms.genre (genre_name) VALUES ('Horror');
INSERT INTO lms.genre (genre_name) VALUES ('Mystery');
INSERT INTO lms.genre (genre_name) VALUES ('Paranormal romance');
INSERT INTO lms.genre (genre_name) VALUES ('Picture book');
INSERT INTO lms.genre (genre_name) VALUES ('Poetry');
INSERT INTO lms.genre (genre_name) VALUES ('Political thriller');
INSERT INTO lms.genre (genre_name) VALUES ('Romance');
INSERT INTO lms.genre (genre_name) VALUES ('Satire');
INSERT INTO lms.genre (genre_name) VALUES ('Science fiction');
INSERT INTO lms.genre (genre_name) VALUES ('Short story');
INSERT INTO lms.genre (genre_name) VALUES ('Suspense');
INSERT INTO lms.genre (genre_name) VALUES ('Thriller');
INSERT INTO lms.genre (genre_name) VALUES ('Young adult');
INSERT INTO lms.genre (genre_name) VALUES ('Art');
INSERT INTO lms.genre (genre_name) VALUES ('Autobiography');
INSERT INTO lms.genre (genre_name) VALUES ('Biography');
INSERT INTO lms.genre (genre_name) VALUES ('Book review');
INSERT INTO lms.genre (genre_name) VALUES ('Cookbook');
INSERT INTO lms.genre (genre_name) VALUES ('Diary');
INSERT INTO lms.genre (genre_name) VALUES ('Dictionary');
INSERT INTO lms.genre (genre_name) VALUES ('Encyclopedia');
INSERT INTO lms.genre (genre_name) VALUES ('Guide');
INSERT INTO lms.genre (genre_name) VALUES ('Health');
INSERT INTO lms.genre (genre_name) VALUES ('History');
INSERT INTO lms.genre (genre_name) VALUES ('Journal');
INSERT INTO lms.genre (genre_name) VALUES ('Math');
INSERT INTO lms.genre (genre_name) VALUES ('Memoir');
INSERT INTO lms.genre (genre_name) VALUES ('Prayer');
INSERT INTO lms.genre (genre_name) VALUES ('Religion, spirituality, and new age');
INSERT INTO lms.genre (genre_name) VALUES ('Textbook');
INSERT INTO lms.genre (genre_name) VALUES ('Review');
INSERT INTO lms.genre (genre_name) VALUES ('Science');
INSERT INTO lms.genre (genre_name) VALUES ('Self help');
INSERT INTO lms.genre (genre_name) VALUES ('Travel');
INSERT INTO lms.genre (genre_name) VALUES ('True crime');

-- publisher
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Penguin Random House','1745 Broadway, New York, NY 10019','18007932665','penguin_random_house@facebook.com','traditional','1946-10-16','980');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Hachette Livre','58 Rue Jean Bleuzen, 92170 Vanves, France','33143923000','hachette_livre@hotmail.com','independent','1991-08-06','982');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Springer Nature','233 Spring St, New York, NY 10013','12124601500','springer@nature.com','traditional','1948-07-08','981');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Scholastic','557 Broadway, New York, NY 10012','18007246527','scholastic@facebook.com','scientific','1980-06-17','982');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Wiley','7925 Jones Branch, Tysons, VA 22102','17039052800','wiley@hotmail.com','adacmic','1938-12-01','982');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('McGraw-Hill Education','2 Pennsylvania Plaza, New York, NY 10121','16467662000','McGraw_Hill@Education.com','adacmic','1999-08-05','978');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('HarperCollins','195 Broadway, New York, NY 10007','12122077000','HarperCollins@gmail.com','traditional','1943-09-18','983');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Cengage','5191 Natorp Blvd, Mason, OH 45040','15132291000','Cengage@gmail.com','scientific','1989-05-07','981');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Houghton Mifflin Harcourt','28 Claremont Ave, Thornwood, NY 10594','19147472636','Houghton_Mifflin@gmail.com','independent','1952-08-28','979');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Macmillan','175 5th Ave, New York, NY 10010','12122267521','Macmillan@gmail.com','traditional','2002-04-15','983');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Oxford University Press','8120 Woodmont Ave, Bethesda, MD 20814','13018411260','OxfordUniversity@Press.edu','adacmic','1997-10-28','983');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Pearson','19 W 44th St #306, New York, NY 10036','12127307414','Pearson@gmail.com','ebook','1953-05-28','983');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Kodansha','451 Park Ave S 7th floor, New York, NY 10022','19173226200','Kodansha@gmail.com','adacmic','1979-04-26','983');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Shueisha','2510 Hitotsubashi, Tokyo 1018050, Japan','11332545430','Shueisha@gmail.com','independent','1989-05-05','981');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Simon & Schuster','100 Front St, Delran, NJ 08075','18564616500','Simon_Schuster@yahoo.com','traditional','1947-02-03','981');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Grupo Santillana','Artesanos, 6 Tres Cantos, 28760 Spain','34917449060','Grupo_Santillana@gmail.com','ebook','1969-02-27','983');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Bonnier Books','535 King''s Rd, Chelsea Harbour, London','34927499060','BonnierBooks@gmail.com','adacmic','1976-07-22','983');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Editis','30 place d''Italie, Paris,  75013, France','33231535330','Editis@gmail.com','scientific','1936-07-07','978');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Klett','12255 Fair Lakes Pkwy, Fairfax, VA 22033','17039345700','Klett@gmail.com','scientific','1981-07-11','980');
INSERT INTO lms.publisher (name,address,phone_number,email,`type`,establishment_date,isbn_prefix) VALUES ('Egmont Books','1 Nicholas Rd, London W11 4AN, UK','34917454460','Egmont_Books@gmail.com','traditional','1936-06-23','982');

-- author
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Michelle Obama','F','michelle_obama@facebook.com',STR_TO_DATE('1/25/1975','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Trevor Noah','M','trevor_noah@macebook.com',STR_TO_DATE('11/8/1976','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Bill Clinton','M','bill_clinton@macebook.com',STR_TO_DATE('10/10/1982','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('James Patterson','M','james_patterson@macebook.com',STR_TO_DATE('5/5/1985','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('David Sedaris','M','david_sedaris@macebook.com',STR_TO_DATE('2/22/1974','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Bruno Siciliano','M','bruno_siciliano@macebook.com',STR_TO_DATE('3/23/1989','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Oussama Khatib','M','oussama_khatib@macebook.com',STR_TO_DATE('1/9/1981','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Craig Smith','M','craig_smith@macebook.com',STR_TO_DATE('12/16/1989','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Chadda Sarwat','F','chadda_sarwat@facebook.com',STR_TO_DATE('10/8/1986','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Edward Allen','F','edward_allen@facebook.com',STR_TO_DATE('3/28/1986','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Sylvia Mader','F','sylvia_mader@facebook.com',STR_TO_DATE('7/14/1985','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Jeffery A Isaacson','M','jeffery_isaacson@macebook.com',STR_TO_DATE('12/24/1976','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('A.J. Finn','M','a_finn@macebook.com',STR_TO_DATE('6/14/1986','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Carl S Warren','M','carl_warren@macebook.com',STR_TO_DATE('9/22/1974','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('James M Reeve','M','james_reeve@macebook.com',STR_TO_DATE('11/15/1978','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Jonathan Duchac','M','jonathan_duchac@macebook.com',STR_TO_DATE('5/14/1974','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Sara Baume','F','sara_baume@facebook.com',STR_TO_DATE('1/13/1983','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Michael Wolff','M','michael_wolff@macebook.com',STR_TO_DATE('10/26/1980','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('James Murray','M','james_murray@macebook.com',STR_TO_DATE('7/2/1985','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Gary L. Peterson','M','gary_peterson@macebook.com',STR_TO_DATE('4/6/1976','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('James S. Sochacki','M','james_sochacki@macebook.com',STR_TO_DATE('2/9/1979','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Hajime Isayama','M','hajime_isayama@macebook.com',STR_TO_DATE('11/26/1987','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Nakaba Suzuki','M','nakaba_suzuki@macebook.com',STR_TO_DATE('10/2/1986','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Oda Eiichiro','M','oda_eiichiro@macebook.com',STR_TO_DATE('9/20/1984','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Yoshihiro Togashi','M','yoshihiro_togashi@macebook.com',STR_TO_DATE('11/26/1982','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Bob Woodward','M','bob_woodward@macebook.com',STR_TO_DATE('9/1/1980','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES (' Antonio Moz Molina','M','antonio_molina@macebook.com',STR_TO_DATE('1/20/1978','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Lily Allen','F','lily_allen@facebook.com',STR_TO_DATE('5/2/1978','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Michael C Nelson','M','michael_nelson@macebook.com',STR_TO_DATE('2/22/1989','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Stephen Hawking','M','stephen_hawking@macebook.com',STR_TO_DATE('11/1/1989','%m/%d/%Y'));
INSERT INTO lms.author (name,gender,email,dob) VALUES ('Laura Ellen Anderson','F','laura_anderson@facebook.com',STR_TO_DATE('9/18/1990','%m/%d/%Y'));

-- library_branch
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Library of Ashurbanipal','20 Hardland Ave, Fairbanks Ashipal, 99709','Monday - Friday: 9am - 5pm','9665997867',111,'libraryofashurbanipal@sbcglobal.net');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Library of Alexandria','519 Carolyn St Kodiak, Alexandria, 99615','Tuesday - Saturday: 10am - 6pm','9050754619',135,'libraryofalexandria@icloud.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Library of Pergamum','519 Lignite Ave, Fairbanks Pergamum, 99701','Monday - Saturday: 8am - 8pm','2905539652',122,'libraryofpergamum@verizon.net');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('The Villa of the Papyri','1108 Healdville Rd., Mount Hy Papyri, 05758','Wednesday - Sunday: 12pm - 8pm','2396494171',124,'thevillaofthepapyri@verizon.net');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Library of Celsus','1115 River Rd, Manchester Vermont, 05255','Monday - Friday: 7am - 9pm','593981624',100,'library_of_celsus@gmail.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('The Imperial Library of Constantinople','1519 Fairhill Dr, Ashland Kentucky, 41102','Tuesday - Saturday: 9am - 7pm','168947524',120,'theimperiallibraryofconstantinople@gmail.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('The House of Wisdom','413rd Rd, Gothenburg Nebraska, 69138','Monday - Thursday: 10am - 9pm, Friday - Saturday: 10am - 10pm','8876669059',143,'thehouseofwisdom@hotmail.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('New York Public Library','23 Peters Ave., East Meadow New York, 11554','Monday - Friday: 8am - 6pm, Saturday: 9am - 2pm','8935268019',144,'newyorkpubliclibrary@verizon.net');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Brooklyn Public Library','38 Costello Rd, Brooklyn Connecticut, 06234','Tuesday - Thursday: 11am - 9pm, Friday - Saturday: 11am - 10pm, Sunday: 12pm - 8pm','3232527320',131,'brooklynpubliclibrary@yahoo.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('National Library of China','817 West Ave, Beijing China, 63545','Monday - Friday: 6am - 10pm, Saturday - Sunday: 7am - 9pm','3414620078',148,'nationallibraryofchina@sbcglobal.net');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('State Library of Victoria','3550 Hancock Ave, Butte Montana, 59701','Monday - Friday: 9am - 5pm','755120952',111,'state.library.of.victoria@yahoo.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Library of Congress','17Fenton Rd., Bainbridge Washington, 98110','Tuesday - Saturday: 10am - 6pm','5207834589',135,'libraryofcongress@hotmail.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('British Library','342 Wyatt NE, Bainbridge Great Britain, 98110','Monday - Friday: 9am - 5pm','329637706',122,'british_library@me.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Royal Danish Library','1307 Clarkwood Dr, Plant City Florida, 33566','Tuesday - Saturday: 10am - 6pm','8374652542',124,'royal.danish.library@gmail.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Berlin State Library','12 Old Pocet Ln, Johnston Rhode Island, 02919','Monday - Saturday: 8am - 8pm','9997516520',100,'berlin.state.library@icloud.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Russian State Library','3 khovaya Street, Vozenka Moscow, Russia','Monday - Friday: 9am - 5pm','6745881746',120,'russian_state_library@gmail.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Bibliothque nationale de France','Quai Franois Mauriac, 75706 Paris, France','Tuesday - Saturday: 10am - 6pm','2803224154',143,'bibliothque_nationale_de_france@aol.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('National Library of Russia','3 khovsky Street, Prisada Moscow 1019, Russia','Monday - Saturday: 8am - 8pm','2958316206',144,'national_library_of_russia@yahoo.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('Trinity College Library','5301 Wnson Rd, Denver NorthCarolina, 28037','Wednesday - Sunday: 12pm - 8pm','1954754011',131,'trinity_college_library@yahoo.com');
INSERT INTO lms.library_branch (name,address,hours_of_operation,phone_number,capacity,email) VALUES ('BODLEIAN LIBRARY','533 Augusta Ln Cary, Illinois, 60013','Monday - Friday: 7am - 9pm','2716288640',148,'bodleianlibrary@icloud.com');

-- access_level
INSERT INTO lms.lms_access_level (name,description) VALUES ('Cataloging',' Allows librarians to add, edit, or delete books from the library''s catalog or database');
INSERT INTO lms.lms_access_level (name,description) VALUES ('Circulation ','Allows librarians to check out, check-in, or renew books for patrons');
INSERT INTO lms.lms_access_level (name,description) VALUES ('Supervisor ','Allows librarians to manage and oversee other librarians');
INSERT INTO lms.lms_access_level (name,description) VALUES ('Administrative','Allows librarians to access and manage library-wide systems and information, such as budgeting and reporting');

-- librarian
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('David Barnes','david_barnes@me.com','5926800213','79772 Orozco Vista Apt. 049 Port Joytown, HI 13512','519-19-9565','Deborah Hansen 0886952031 deborah_hansen@aol.com',9,4);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Rebecca King','rebecca_king@sbcglobal.net','4691952671','73725 Garcia Alley East Allison, NC 54998','146-74-3122','Ann Brown 8460483435 annbrown@sbcglobal.net',8,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Ana Hill','ana.hill@icloud.com','4459437480','12923 Gould Plain Apt. 071 Lake Richard, IL 37119','779-65-4856','Rachel Turner 4574611920 rachelturner@icloud.com',10,4);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Michael Garcia','michael.garcia@verizon.net','4961005270','8182 Shelby Highway Thomasburgh, AK 60296','465-35-1277','Olivia Dominguez 9430376819 olivia_dominguez@gmail.com',7,4);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Benjamin Charles','benjamin_charles@icloud.com','4006086674','720 Reginald Mountains Suite 728 Meyersstad, SC 64228','151-07-1407','Robert Duffy 4170827277 robert_duffy@me.com',3,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Amy Castillo','amycastillo@yahoo.com','182991987','900 Vaughn Vista Suite 814 New Alishaville, ME 28637','848-53-5097','Richard Estes 6043998115 richard.estes@me.com',7,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Terry Hall','terryhall@sbcglobal.net','3265274646','50672 James Hollow Lake Jasminehaven, NH 62035','763-40-4181','Jennifer Richards 4663839190 jennifer_richards@icloud.com',2,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Kyle Green MD','kyle_green@icloud.com','2710687742','52999 Garcia Curve Petersonburgh, MN 41066','530-01-8524','Richard Reyes 6610046904 richard.reyes@aol.com',2,4);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Alyssa Santos','alyssa.santos@aol.com','4176347456','92998 Austin Passage Olsonview, NE 79523','407-82-7780','Mark Powell 4481459047 markpowell@yahoo.com',3,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Tracy Brown','tracy_brown@verizon.net','9798130145','2080 William Mount Suite 494 East Matthew, NC 90115','445-61-3979','Brandon Diaz 5220930446 brandon_diaz@yahoo.com',6,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Anthony Greer','anthony_greer@aol.com','7326719375','98124 Catherine View Apt. 611 East Danielle, MI 60626','129-28-7238','Eric Owen 1939215898 eric_owen@me.com',7,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Darren Perez','darrenperez@yahoo.com','1764964281','Unit 4806 Box 7197 DPO AP 48487','451-93-6865','Jose White 3895626482 jose_white@icloud.com',9,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Gary Woods','gary.woods@verizon.net','6370407437','06715 Justin Mountains New Jamesburgh, ND 21356','028-27-4368','Heidi Carter 3146414222 heidi_carter@sbcglobal.net',7,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Jeffrey Brooks','jeffrey_brooks@icloud.com','4250976241','1615 Boyle Burg Tammyton, OH 55655','354-06-4864','Ronald Turner 9430893762 ronald_turner@me.com',7,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Amy Baker','amybaker@aol.com','7059190641','76362 Matthew Dam Suite 426 Davidside, DE 00999','751-47-2201','Martha Martin 8449099776 martha_martin@yahoo.com',8,1);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Stephen Hart','stephenhart@me.com','8352795494','5564 Steven Plaza North Nicholasview, IA 46413','463-24-6350','Katherine Newton 0601329523 katherine_newton@yahoo.com',3,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Chad Bryan','chadbryan@hotmail.com','4801945663','493 Gary Isle Apt. 385 Martinport, IA 56168','744-32-1414','Mr. Adam Schneider MD 2198446870 mradam@me.com',1,1);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Jason Carney','jason_carney@icloud.com','1307619694','2324 Butler Roads Suite 172 South Lacey, IL 36785','252-40-7510','Andrew Gonzalez 5811003455 andrewgonzalez@me.com',6,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Sierra Mitchell','sierra.mitchell@aol.com','8123285207','184 Sweeney Loop Port Keith, MI 14304','811-49-8748','Suzanne Wilson 4559802250 suzanne.wilson@sbcglobal.net',5,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Maria Castro','maria_castro@aol.com','6924384933','00360 Tonya Junction Mollychester, IA 90006','055-65-1177','Megan Henson 3275764394 megan.henson@aol.com',7,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Angela Willis','angela_willis@aol.com','8688602296','823 Kelley Fork East Michael, WV 04393','205-86-5594','Derek Hobbs 8486335953 derek.hobbs@yahoo.com',6,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Jonathon Morton','jonathon_morton@verizon.net','2957554701','904 Rivera Manor Suite 149 Ebonytown, NM 91209','687-75-2009','Julia Poole 8738372015 julia_poole@gmail.com',5,1);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Terry Mitchell PhD','terrymitchell@icloud.com','8680210515','68663 Small Way Lake Hollyfort, MO 47948','807-35-7245','Ashlee Lutz 5613620516 ashlee_lutz@gmail.com',7,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Kimberly Morris','kimberly.morris@verizon.net','9063244957','734 Butler Turnpike Suite 215 New Bruceport, PA 43684','035-89-6024','James Cantu 2647512403 jamescantu@aol.com',3,1);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('David Duffy','davidduffy@hotmail.com','4737313407','3454 Miller Ranch West Brentburgh, CA 15902','623-23-2944','Jacob Anderson 7536093597 jacob.anderson@icloud.com',8,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Samantha Arnold','samantha_arnold@sbcglobal.net','946288799','91411 Huynh Land New Monicaberg, MO 23246','160-80-9246','Christopher Garcia 2423263802 christopher_garcia@yahoo.com',9,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Colleen Freeman MD','colleen.freeman@icloud.com','7461748403','PSC 7960, Box 7066 APO AP 67935','464-31-5374','Rebecca Smith 2426278004 rebecca_smith@verizon.net',8,3);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Ann Waters','annwaters@icloud.com','2302385514','72687 Shelly Pines Apt. 953 Richardshire, UT 32301','745-67-5354','Meghan Farmer 6407264185 meghanfarmer@gmail.com',7,1);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Michael Walker','michaelwalker@me.com','5889764290','52345 Johnson Divide South Stephaniefurt, WY 33958','311-30-6364','Olivia Roberts 1453511794 olivia.roberts@gmail.com',2,2);
INSERT INTO lms.librarian (name,email,phone,address,ssn,emergency_contact,library_branch_id,access_level) VALUES ('Karla Perez','karla_perez@me.com','8578068613','08953 Ryan Harbors Haneybury, AK 33241','311-90-6364','Haley Brown 8764048885 haley.brown@verizon.net',3,4);

-- book
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Becoming by Michelle Obama','982-5-25-332098-6',1,2,4401,'pamphlet','English','2015-12-20');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Born a Crime','983-1-69-508758-8',1,1,1545,'hardcover','English','2014-12-10');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('The President is Missing','978-1-75-660489-0',2,3,2234,'hardcover','English','2008-12-01');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Calypso','981-8-72-716392-9',2,2,458,'large_print','French','2014-07-02');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Robotics and the Handbook','980-3-22-986941-7',3,2,6499,'hardcover','English','2010-03-18');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('The Wonky Donkey ','978-9-43-356129-4',4,5,5515,'hardcover','English','2019-12-12');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('The Dragon''s Eye','983-8-16-782525-5',4,5,4071,'large_print','English','2017-06-09');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Fundamentals of Building Construction','978-8-26-808369-9',5,1,6237,'hardcover','English','2019-06-11');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Inquiry into Life','983-7-53-198962-9',6,2,72,'pamphlet','English','2005-06-25');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('The Woman in the Window','983-6-23-753653-1',7,6,3035,'paperback','English','2005-06-14');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Financial & Managerial Accounting','979-9-79-249658-1',8,2,3178,'hardcover','English','2013-12-12');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Spill Simmer Falter Wither','979-1-40-846282-6',9,1,4690,'pamphlet','English','2015-10-09');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Fire and Fury','978-0-80-471819-9',10,7,6374,'paperback','English','2006-06-16');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Oxford English Dictionary','982-8-95-379141-5',11,7,927,'pamphlet','English','2008-04-18');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Linear Algebra and Differential Equations','982-9-40-975636-2',12,3,1539,'softcover','English','2013-02-15');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Attack on Titan','980-1-96-583910-4',13,7,6251,'large_print','English','2013-03-19');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('The Seven Deadly Sins','981-1-44-304937-5',13,2,429,'paperback','English','2005-07-10');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('One Piece','978-7-84-955744-0',14,4,6692,'softcover','English','2009-05-14');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Hunter x Hunter','978-4-16-324446-7',14,2,1890,'pdf','English','2007-08-02');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Fear: Trump in the White House','980-5-22-748809-3',15,2,4454,'paperback','English','2016-04-19');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Sefarad','982-3-13-804871-2',16,5,6262,'paperback','Arabic','2010-10-02');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('My Thoughts Exactly','983-3-90-465423-0',18,4,3646,'large_print','English','2011-05-01');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('The Presidency and the Political System','980-0-84-931638-0',18,1,2250,'paperback','English','2015-12-10');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Kurze Antworten auf Fragen','978-3-81-251599-1',19,4,3714,'pdf','German','2017-07-26');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Little Miss Inventor','983-3-59-860108-6',20,7,6665,'ebook','English','2019-12-30');
INSERT INTO lms.book (title,isbn,publisher_id,edition,total_pages,format,`language`,publication_date) VALUES ('Amelia Fang and the Memory Thief','983-2-58-939342-6',20,2,4907,'pdf','English','2013-10-14');

-- book_author
INSERT INTO lms.book_author (book_id,author_id) VALUES (1,1);
INSERT INTO lms.book_author (book_id,author_id) VALUES (2,2);
INSERT INTO lms.book_author (book_id,author_id) VALUES (3,3);
INSERT INTO lms.book_author (book_id,author_id) VALUES (3,4);
INSERT INTO lms.book_author (book_id,author_id) VALUES (4,5);
INSERT INTO lms.book_author (book_id,author_id) VALUES (5,6);
INSERT INTO lms.book_author (book_id,author_id) VALUES (5,7);
INSERT INTO lms.book_author (book_id,author_id) VALUES (6,8);
INSERT INTO lms.book_author (book_id,author_id) VALUES (7,9);
INSERT INTO lms.book_author (book_id,author_id) VALUES (8,10);
INSERT INTO lms.book_author (book_id,author_id) VALUES (9,11);
INSERT INTO lms.book_author (book_id,author_id) VALUES (9,12);
INSERT INTO lms.book_author (book_id,author_id) VALUES (10,13);
INSERT INTO lms.book_author (book_id,author_id) VALUES (11,14);
INSERT INTO lms.book_author (book_id,author_id) VALUES (11,15);
INSERT INTO lms.book_author (book_id,author_id) VALUES (11,16);
INSERT INTO lms.book_author (book_id,author_id) VALUES (12,17);
INSERT INTO lms.book_author (book_id,author_id) VALUES (13,18);
INSERT INTO lms.book_author (book_id,author_id) VALUES (14,19);
INSERT INTO lms.book_author (book_id,author_id) VALUES (15,20);
INSERT INTO lms.book_author (book_id,author_id) VALUES (15,21);
INSERT INTO lms.book_author (book_id,author_id) VALUES (16,22);
INSERT INTO lms.book_author (book_id,author_id) VALUES (17,23);
INSERT INTO lms.book_author (book_id,author_id) VALUES (18,24);
INSERT INTO lms.book_author (book_id,author_id) VALUES (19,25);
INSERT INTO lms.book_author (book_id,author_id) VALUES (20,26);
INSERT INTO lms.book_author (book_id,author_id) VALUES (21,27);
INSERT INTO lms.book_author (book_id,author_id) VALUES (22,28);
INSERT INTO lms.book_author (book_id,author_id) VALUES (24,30);
INSERT INTO lms.book_author (book_id,author_id) VALUES (26,29);
INSERT INTO lms.book_author (book_id,author_id) VALUES (26,31);

-- book_copies
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,1,10);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,2,21);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,3,12);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,4,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,5,11);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,6,12);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,7,4);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,8,56);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,9,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,10,7);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,11,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,12,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,13,47);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,14,46);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,15,6);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,16,46);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,17,46);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,18,4);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,19,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (1,20,40);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,1,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,2,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,3,33);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,4,38);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,5,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,6,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,7,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,8,37);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,9,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,10,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,11,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,12,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,13,26);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,14,38);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,15,11);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,16,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (2,17,48);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,1,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,2,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,3,12);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,4,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,5,9);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,6,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,7,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,8,2);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,9,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,10,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,11,11);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,12,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,13,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,14,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,15,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (3,16,48);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,1,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,2,16);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,3,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,4,3);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,5,31);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,6,43);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,7,42);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,8,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,9,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,10,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,11,39);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,12,30);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,13,5);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,14,33);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,17,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,18,30);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,19,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (4,20,31);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,1,34);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,2,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,3,47);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,4,3);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,5,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,6,43);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,7,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,8,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,9,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,10,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,11,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,12,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,13,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,14,15);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,15,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,16,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,17,17);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,18,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,19,28);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (5,20,21);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,1,7);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,2,48);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,3,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,4,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,5,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,6,15);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,7,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,8,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,16,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,17,50);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,18,50);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,19,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,20,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,21,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,22,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,23,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,24,17);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,25,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (6,26,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,1,34);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,2,4);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,3,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,9,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,10,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,11,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,12,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,13,39);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,14,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,15,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,16,12);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,17,48);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,18,0);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,19,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,20,3);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,21,28);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,22,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,23,50);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,24,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,25,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (7,26,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,4,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,5,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,6,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,7,22);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,8,19);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,9,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,10,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,11,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,12,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,13,6);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,14,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,15,42);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,16,39);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (8,17,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,1,4);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,2,46);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,3,30);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,4,42);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,5,19);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,18,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,19,39);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,20,47);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,21,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,22,42);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,23,16);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (9,24,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,6,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,7,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,8,17);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,9,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,10,19);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,11,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,12,17);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,13,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,14,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,15,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,16,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,17,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,18,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,19,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,20,15);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,21,10);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,22,5);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,23,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (10,24,5);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,1,7);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,2,35);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,3,28);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,4,40);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,5,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,6,42);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,7,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,8,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,9,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,10,3);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,11,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,12,24);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,13,24);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,14,43);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,15,37);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,16,13);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,17,0);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,18,47);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,25,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (11,26,24);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,1,47);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,2,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,3,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,4,19);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,5,16);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,6,2);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,7,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,8,22);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,9,39);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,19,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,20,22);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,21,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,22,50);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,23,12);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,24,33);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,25,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (12,26,0);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,10,47);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,11,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,12,6);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,13,5);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,14,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,15,26);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,16,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,17,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,18,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,19,47);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,20,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,21,22);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,22,13);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,23,48);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (13,24,38);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,1,7);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,2,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,3,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,4,4);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,5,32);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,6,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,7,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,8,28);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,25,3);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (14,26,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,9,21);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,10,27);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,11,31);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,12,0);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,13,37);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,14,37);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,15,10);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,16,17);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,17,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (15,18,38);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,1,42);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,2,40);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,19,4);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,20,50);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,21,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,22,11);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,23,9);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,24,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,25,31);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (16,26,20);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,3,31);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,4,17);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,5,9);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,6,33);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,7,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,8,13);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,9,11);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,10,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,11,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (17,12,36);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,13,38);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,14,43);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,15,29);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,16,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,17,15);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,18,43);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,19,2);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,20,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,21,10);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (18,22,37);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,1,14);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,2,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,3,45);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,4,50);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,5,0);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,6,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,7,25);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,8,23);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,9,41);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,10,38);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,23,4);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,24,49);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,25,18);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (19,26,5);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,1,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,2,44);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,3,26);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,11,8);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,12,7);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,13,30);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,14,2);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,15,24);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,16,1);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,17,31);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,18,48);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,19,13);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,20,3);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,21,33);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,22,15);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,23,46);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,24,6);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,25,7);
INSERT INTO lms.book_copies (library_branch_id,book_id,no_of_copies) VALUES (20,26,45);

-- book_genre
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (1,20);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (1,23);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (1,28);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (2,8);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (2,21);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (2,23);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (2,28);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (3,9);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (3,28);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (3,29);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (4,9);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (4,12);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (5,22);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (5,25);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (6,3);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (6,5);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (6,7);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (7,17);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (8,35);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (8,39);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (8,45);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (9,11);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (10,1);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (11,35);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (11,39);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (11,43);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (12,30);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (12,41);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (13,9);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (14,33);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (15,39);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (15,43);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (16,1);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (16,8);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (16,11);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (16,24);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (17,1);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (17,25);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (18,1);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (18,11);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (19,1);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (19,12);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (19,15);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (20,28);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (21,36);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (22,42);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (23,19);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (24,16);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (24,18);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (24,21);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (24,25);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (24,45);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (25,30);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (26,9);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (26,10);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (26,11);
INSERT INTO lms.book_genre (book_id,genre_id) VALUES (26,12);

-- user
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Adekunle Gold','Musician','M','9997696334','adekunle.gold@hotmail.com','7364 N. Branch Street,Norcross, GA 30092');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('John Kenedy','President','M','5509731057','johnkenedy@aol.com','1 Cedar Swamp St., West Chester, PA 19380');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Gaven Arroyo','Student','M','7207563352','gaven.arroyo@gmail.com','936 North Riverside St., Livingston, NJ 07039');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Kimberly Mathis','Doctor','F','8187807021','kimberlymathis@yahoo.com','843 Park Ave.Superior, WI 54880');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Karley Mendoza','Lawyer','F','8924468102','karley.mendoza@gmail.com','7178 Monroe Street, Coventry, RI 02816');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Hudson Guerrero','Military','M','3929470139','hudson_guerrero@yahoo.com','363 South Forest Drive, Downingtown, PA 19335');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Dillon Perkins','Student','M','7978043248','dillon_perkins@yahoo.com','6 Greenrose Ave.Forest Hills, NY 11375');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Tiffany Howard','Lawyer','F','9154022365','tiffany.howard@sbcglobal.net','5 Stillwater Ave.Marshalltown, IA 50158');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Laci Mack','Engineer','M','5437835213','laci.mack@sbcglobal.net','238 Hillside Street, Beaver Falls, PA 15010');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Brock Vaughan','Teacher','M','6948190970','brockvaughan@aol.com','327 Newbridge Ave.Charlotte, NC 28205');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Kamryn Franco','Nurse','F','6958816202','kamrynfranco@hotmail.com','638 Oxford St.Forney, TX 75126');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Leland Humphrey','Student','M','3963132116','leland.humphrey@yahoo.com','125 Berkshire Lane, Gainesville, VA 20155');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Delaney Hayes','Programmer','M','3665484536','delaneyhayes@yahoo.com','41 Newcastle Drive, Little Rock, AR 72209');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Bryce Reilly','Construction worker','M','8175291808','bryce.reilly@hotmail.com','625 Cedar Drive, Starkville, MS 39759');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Dominick Sutton','Accountant','M','9245083521','dominicksutton@sbcglobal.net','7756 Longbranch Ave.Rockledge, FL 32955');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Melanie Lang','Electrician','F','4942677915','melanielang@yahoo.com','535 North Annadale Drive, San Jose, CA 95127');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Jorge Ellison','Student','M','4295990856','jorge.ellison@gmail.com','8237 Arrowhead St.Derry, NH 03038');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Danny Wise','Firefighter','M','2229480869','dannywise@me.com','45 W. Shore Rd.Janesville, WI 53546');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Juan Wheeler','Chef','M','9815919789','juan.wheeler@gmail.com','248 NE. Willow Ave.Cincinnati, OH 45211');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Claudia Franco','Artist','M','6934956665','claudia_franco@me.com','9186 Saxton Road. New Orleans, LA 70115');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Todd Craig','Student','M','8477237811','todd_craig@hotmail.com','8563 Harvard Court, Muskegon, MI 49441');
INSERT INTO lms.user (name,occupation,gender,phone,email,address) VALUES ('Dominick George','Dentist','M','7872849405','dominick.george@yahoo.com','83 Van Dyke St.Floral Park, NY 11001');

-- loan_record
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (1,1,1,'2019-01-22 00:00:00','2019-01-29 00:00:00','2019-01-29 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (1,2,26,'2019-02-16 00:00:00','2019-02-23 00:00:00','2019-02-22 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (2,2,2,'2019-01-23 00:00:00','2019-01-30 00:00:00','2019-01-30 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (2,6,5,'2019-02-20 00:00:00','2019-02-27 00:00:00','2019-02-21 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (3,2,23,'2019-02-13 00:00:00','2019-02-20 00:00:00','2019-02-20 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (3,3,3,'2019-01-24 00:00:00','2019-01-31 00:00:00','2019-01-29 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (3,9,6,'2019-02-21 00:00:00','2019-02-28 00:00:00','2019-02-27 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (4,3,8,'2019-02-22 00:00:00','2019-03-01 00:00:00','2019-03-01 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (4,4,4,'2019-01-25 00:00:00','2019-02-01 00:00:00','2019-01-28 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (5,4,24,'2019-02-14 00:00:00','2019-02-21 00:00:00','2019-02-20 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (5,5,5,'2019-01-26 00:00:00','2019-02-02 00:00:00','2019-01-28 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (5,11,23,'2019-02-23 00:00:00','2019-03-02 00:00:00','2019-02-27 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (6,1,25,'2019-02-15 00:00:00','2019-02-22 00:00:00','2019-02-18 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (6,6,6,'2019-01-27 00:00:00','2019-02-03 00:00:00','2019-02-03 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (7,7,7,'2019-01-28 00:00:00','2019-02-04 00:00:00','2019-02-04 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (8,8,8,'2019-01-29 00:00:00','2019-02-05 00:00:00','2019-02-02 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (8,14,4,'2019-02-24 00:00:00','2019-03-03 00:00:00','2019-03-03 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (8,20,1,'2019-02-17 00:00:00','2019-02-24 00:00:00','2019-02-18 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (9,9,9,'2019-01-30 00:00:00','2019-02-06 00:00:00','2019-02-01 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (10,10,10,'2019-01-31 00:00:00','2019-02-07 00:00:00','2019-02-07 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (11,2,21,'2019-02-28 00:00:00','2019-03-07 00:00:00','2019-03-02 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (11,6,18,'2019-03-01 00:00:00','2019-03-08 00:00:00','2019-03-03 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (11,11,11,'2019-02-01 00:00:00','2019-02-08 00:00:00','2019-02-03 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (12,12,12,'2019-02-02 00:00:00','2019-02-09 00:00:00','2019-02-04 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (12,16,2,'2019-02-25 00:00:00','2019-03-04 00:00:00','2019-02-26 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (13,13,13,'2019-02-03 00:00:00','2019-02-10 00:00:00','2019-02-09 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (14,14,14,'2019-02-04 00:00:00','2019-02-11 00:00:00','2019-02-11 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (15,11,1,'2019-02-19 00:00:00','2019-02-26 00:00:00','2019-02-22 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (15,12,22,'2019-02-27 00:00:00','2019-03-06 00:00:00','2019-03-02 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (15,15,15,'2019-02-05 00:00:00','2019-02-12 00:00:00','2019-02-10 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (16,16,16,'2019-02-06 00:00:00','2019-02-13 00:00:00','2019-02-11 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (17,10,17,'2019-02-26 00:00:00','2019-03-05 00:00:00','2019-03-05 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (17,17,17,'2019-02-07 00:00:00','2019-02-14 00:00:00','2019-02-12 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (18,18,18,'2019-02-08 00:00:00','2019-02-15 00:00:00','2019-02-13 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (19,19,19,'2019-02-09 00:00:00','2019-02-16 00:00:00','2019-02-13 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (20,10,3,'2019-02-18 00:00:00','2019-02-25 00:00:00','2019-02-21 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (20,20,20,'2019-02-10 00:00:00','2019-02-17 00:00:00','2019-02-11 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (21,3,21,'2019-02-11 00:00:00','2019-02-18 00:00:00','2019-02-18 00:00:00');
INSERT INTO lms.loan_record (user_id,library_branch_id,book_id,loan_date,due_date,date_in) VALUES (22,4,22,'2019-02-12 00:00:00','2019-02-19 00:00:00','2019-02-16 00:00:00');
